
java_library(
    name='project1',
    srcs=glob(["src/java/**/*.java"]),
    deps=[
        "@aopalliance//jar",
        # Commented out: this will cause project1 to fail to build,
        # but will show up as OK in IntelliJ
        #"@guice_4_1//jar",
    ],


)
